### ISSUE TITLE
Problems with k3d_vector and Ubermag.test

### ISSUE THREAD

**Issue by pikean** [ubermag/workshop#27] opened 2020-06-30 02:27 UTC
I get the error "AttributeError: Object has no attribute k3d_vector" when I try to use k3d_vector in the tutorial notebooks. To try to fix this I have updated ubermag with "conda update ubermag" in the Anaconda powershell prompt and then restarted my computer, but I still get the error.

I also have issues with the Ubermag.test. I get 1 failure on test_overhead and 34 warnings.  The test summary is pasted below:

=============================================== short test summary info ===============================================
FAILED tests/test_oommf.py::test_overhead - RuntimeError: Error in OOMMF run.
================== 1 failed, 288 passed, 1 skipped, 5 deselected, 34 warnings in 1712.56s (0:28:32) ===================

I'm not sure if these are two separate issues or if they are related in some way.

Thanks in advance!

**Comment by marijanbeg** [comment] 2020-06-30 09:09
Hi @pikean, thank you for your question. The errors you get look like ubermag is not updated. Have you updated it in the right conda environment? What operating system you use?

**Comment by pikean** [comment] 2020-06-30 17:57
Hi @marijanbeg. My operating system is Windows 10. I updated in the environment that I created to install Ubermag, but then forgot to launch Jupyter in that environment. Now that Jupyter is running in the correct environment I am able to use k3d_vector.

The test failure still stands, though. Is that anything to be concerned about?

**Comment by marijanbeg** [comment] 2020-07-01 07:01
Hi @pikean, thank you for your update. Regarding tests: Although this tests is not crucial, all tests should pass. Did you run tests in a clean directory as we showed in installation instructions?

**Comment by marijanbeg** [comment] 2020-07-01 22:47
I am going to close this issue now, but if the problem is still there, please feel free to reopen :)

**Closed by marijanbeg** 2020-07-01 22:47 UTC
