### ISSUE TITLE
How to write equation of circle?

### ISSUE THREAD

**Issue by gaurav123shukla** [ubermag/workshop#28] opened 2020-06-30 05:24 UTC
Dear sir
Please help me for this problem.I could not write equation of circle.
Email: gauravshukla571996@gmail.com

![prob](https://user-images.githubusercontent.com/67150548/86086218-33b72c00-ba6f-11ea-91ed-9e4329cc349f.JPG)

![radius0](https://user-images.githubusercontent.com/67150548/86086294-6103da00-ba6f-11ea-8593-a49de58102d1.JPG)
![radius](https://user-images.githubusercontent.com/67150548/86086320-72e57d00-ba6f-11ea-9d91-fe9001bb6148.JPG)
![radius1](https://user-images.githubusercontent.com/67150548/86086346-84c72000-ba6f-11ea-9c49-8ce8be86f81c.JPG)

**Comment by marijanbeg** [comment] 2020-06-30 09:07
Hi @gaurav123shukla, the circle equation is `(x-x0)**2 + (y-y0)**2 < r**2` for a circle with its centre at (x0, y0) and radius r. (https://en.wikipedia.org/wiki/Circle)

**Comment by gaurav123shukla** [comment] 2020-07-03 17:00
Sir please see my above figure ,only 1/4 circle (left below corner) is showing. I think i am making mistake to write the problem in the jupyter notebook.
I write  it again but i am finding the same figure. Please check my file and suggest me.

[skyrmion.pdf](https://github.com/ubermag/workshop/files/4870715/skyrmion.pdf)
![1](https://user-images.githubusercontent.com/67150548/86487739-e831a600-bd2c-11ea-838b-d2a39c67084c.JPG)
![2](https://user-images.githubusercontent.com/67150548/86487744-eb2c9680-bd2c-11ea-9589-1aecb9881c84.JPG)
![radius1](https://user-images.githubusercontent.com/67150548/86487747-eff14a80-bd2c-11ea-9b06-af34e1056c84.JPG)

**Comment by marijanbeg** [comment] 2020-07-03 17:10
Hi @gaurav123shukla, for example if you want a circle with 20nm radius in the middle of your sample, you write:

```
def m_init(point):
    x, y, z = point
    if (x-L/2)**2 + (y-w/2)**2 < 20e-9**2:
        return (0, 0, -1)
    else:
        return (0, 0, 1)
```

I would suggest you try this function first and then extend it for what you need.

**Comment by marijanbeg** [comment] 2020-07-03 18:37
Hi @gaurav123shukla, did this work? Could you please let us know when the problem is solved, so we can close the issue?

**Comment by gaurav123shukla** [comment] 2020-07-03 18:39
Yes sir, it worked, thank you very much sir.

**Comment by marijanbeg** [comment] 2020-07-03 18:40
Great, thank you for letting me know.

I am closing this issue now.

**Closed by marijanbeg** 2020-07-03 18:40 UTC
