### ISSUE TITLE
Generating .mif files

### ISSUE THREAD

**Issue by Ayers6991** [ubermag/workshop#66] opened 2020-09-13 21:00 UTC
Hi,
Generated .mif file from the python code in the problem of "Skyrmion in a Disc" is not running in OOMMF. It is showing some errors.

**Comment by marijanbeg** [comment] 2020-09-15 09:02
Hi @Ayers6991, thank you very much for your question. From your issues, I cannot understand what the problem is, but the most possible is that you are running simulations with DMI of crystallographic class T on Windows, where that OOMMF extension does not exist. You can refer to this issue: https://github.com/ubermag/workshop/issues/15 where we explained how this problem can be solved using Docker.

I am going to close this issue now, but if my answer did not address your questions, please feel free to reopen it.

**Closed by marijanbeg** 2020-09-15 09:02 UTC
